apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - "./infra/k8s/*"

build:
  local:
    push: false
  artifacts:
    - image: insaiyadin/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: "src/**/*.ts"